<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <base href="<?php echo BASE_URL ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <title>TPE entrega 2</title>
</head>

<body>
    <header>
        
        <nav class="navbar navbar-expand-lg bg-dark justify-content-center">
            <?php if(!isset($_SESSION)) :?>
                <ul class="nav nav-underline">
                <li class="nav-item">
                    <a class="nav-link" href="inicioSesion">iniciar sesion</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="registro">registrarse</a>
                </li>
            <?php endif ?>
            <?php if(isset($_SESSION)) :?>    
            <ul class="nav nav-underline">
                <li class="nav-item">
                    <a class="nav-link" href="cerrarSesion">cerrar sesion</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="miPerfil">mi perfil</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="verSocios">ver socios</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="verSuscripciones">ver suscripciones</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="verNoticias">ver noticias</a>
                </li>
                <?php endif ?>
            </ul>
    </header>