<?php require_once './templates/header.phtml';?>

<h1>BIENVENIDO DE VUELTA <?php echo strtoupper($nombre) ?></h1>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Tu EMAIL es: <?php echo $email ?></th>
    </tr>
  </thead>
  <tbody>
   <!-- <tr>
      <th scope="row">Tu tipo de Subscripcion es: <?php  ?></th>
    </tr> -->
    <tr>
      <th scope="row">Tu Nombre es: <?php echo $nombre?></th>
    </tr>
    <tr>
      <th scope="row">Tu subscripcion es: <?php if(empty($plan->tipo)) :
        echo 'NO POSEE SUBSCRIPCION ACTIVA'; ?>
        <?php else :
          echo $plan->tipo ?></th>
        <?php endif ?>
    </tr>
    <?php if($esAdmin) : ?>
      <tr>
      <th scope="row">Usted es un ADMINISTRADOR</th>
      </tr>
    <?php endif ?>
  </tbody>
</table>
<form action="cambiarNombre" method="POST">
    <label for="cambio-nombre">CAMBIAR NOMBRE DE USUARIO</label>
    <input type="text" name="cambio-nombre">
    <button type="submit">CAMBIAR</button>
    </form>