<?php include_once 'Templates/header.phtml'; ?>
<table class='table'>
  <thead>
    <form action="filtro" method="POST">
      <tr>
        <td>
          <button><a href="verSuscripciones" class="text-decoration-none text-dark">MOSTRAR TODAS</a></button>
        </td>
        <td>
          <label for="filtro-sector">SECTOR</label>
          <select name="filtro-sector">
            <option value="POPULAR">POPULAR</option>
            <option value="PLATEA">PLATEA</option>
            <option value="PALCO">PALCO</option>
          </select>
        </td>
        <td>
          <input type="number" name="filtro-precio-min" placeholder="precio minimo">
          <input type="number" name="filtro-precio-max" placeholder="precio maximo">
        </td>
        <td>
          <input type="number" name="filtro-duracion-min" placeholder="duracion minimo">
          <input type="number" name="filtro-duracion-max" placeholder="duracion maximo">
        </td>
        <td><button type="submit">filtrar</button></td>
      </tr>
    </form>
    <tr>
      <th scope='col'>SUSCRIPCION</th>
      <th scope='col'>SECTOR DE ENTRADA</th>
      <th scope='col'>PRECIO</th>
      <th scope='col'>DURACION(AÑOS)</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <?php
    foreach ($subscripciones as $subscripcion) : ?>
      <tr>
        <td> <?php echo $subscripcion->tipo ?></td>
        <td> <?php echo $subscripcion->caracteristicas ?></td>
        <td> <?php echo $subscripcion->precio ?> $USD</td>
        <td> <?php echo $subscripcion->duracion ?></td>
        <?php if($esAdmin) : ?>
        <td><form action="eliminarSub" method="POST">
        <input type="hidden" name="id_a_eliminar" value="<?php echo $subscripcion->ID_subscripcion; ?>">
        <button type="submit">eliminar</button></form>
        <form action="" method="POST">
        <input type="hidden" name="id_editar" value="<?php echo $subscripcion->ID_subscripcion; ?>">
        <button type="submit">editar</button></form></td>
        <?php endif ?>
      </tr>
    <?php endforeach ?>
    <?php if($esAdmin) : ?>
  <form action="agregarSub" method="POST">
    <tr>
      <td>
      <input type="text" name="nuevo-nombre" placeholder="Ingrese nuevo nombre">
      </td>
      <td>
      <select name="nuevo-sector">
          <option value="POPULAR">POPULAR</option>
          <option value="PLATEA">PLATEA</option>
          <option value="PALCO">PALCO</option>
      </select>
      </td>
      <td>
      <input type="number" name="nuevo-precio" placeholder="ingrese nuevo precio"> $USD
      </td>
      <td>
      <input type="number" name="nuevo-duracion" placeholder="ingrese nueva duracion">
      </td>
      <td><button type="submit">Agregar SUB</button></td>
    </tr>
    </form>
    <?php endif ?>
  </tbody>
</table>